### ISSUE TITLE
Commas inaccurate after pressing backspace.

### ISSUE THREAD

**Issue by tslater** [budiadiono/react-native-calculator#5] opened 2018-12-12 02:06 UTC
The commas become "off" after deleting some numbers.

**Comment by budiadiono** [comment] 2018-12-26 13:23
Hi @tslater, I'm sorry I don't understand, can you explain more detail? And steps to reproduce please?

**Comment by budiadiono** [comment] 2019-02-07 01:29
I'm closing this issue now since I can't find a way to reproduce it. Feel free to reopen this issue for anyone who can give the steps to reproduce this issue.

**Closed as completed by budiadiono** 2019-02-07 01:29 UTC
